name: Run the workflow

on:
  repository_dispatch:
    types: [my-event]

jobs:
  Run-Triggering-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Print echo messages
        run: |
          echo "This is workflow is called by the Build Workflow repository"
