name: Using Secret Token 

on:
  push

jobs:
  Using-Secret-Token:

    runs-on: ubuntu-latest
    steps:
    - name: Using Secret Token to compile and run
      run: |
        if [ "${{ secrets.USER_NAME }}" == "student" ] && [ "${{ secrets.PASSWORD }}" == "student@123" ]; then
          echo "Username and password was correct"
        else
          echo "Invalid username or password"
        fi
        
      
    
